# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration
changelog:
  exclude:
    authors:
      - 'dependabot'
  categories:
    - title: 'New'
      labels:
        - 'feature'
    - title: 'Improved'
      labels:
        - 'docs'
        - 'style'
    - title: 'Refactor'
      labels:
        - 'refactor'
    - title: 'Fixed'
      labels:
        - 'fix'
    - title: 'Documentation'
      labels:
        - 'docs'
    - title: 'Other Changes'
      labels:
        - '*'