name: 'Generate Labels'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    name: 'Label PR based on title'
    runs-on: ubuntu-latest
    steps:
      - name: 'Label PR based on title'
        uses: srvaroa/labeler@v1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Output Labels'
        run: |
          echo "Labels for the PR:"
          for label in $(echo "${{ github.event.pull_request.labels[*] }}" | jq -r '.[].name'); do
            echo "$label"
          done
